name: At Last 2016
favicon: null
layout_spectrum: 0.8839729411993176
typography_spectrum: 0.03252781368792057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#585858'
    - '#021a64'
    - '#f06701'
    - '#bababa'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
